---
title: "International Trade"
author: "Leah, Sam, Thai"
date: "11/19/20"
output:
  rmdformats::readthedown:
    thumbnails: false
    highlight: NULL
---

```{r setup, include=FALSE}
library(tidyverse)
library(evaluate)
library(janitor)
library(lubridate)
library(maps)
library(datasets)
library(gapminder)
library(viridis)
library(ggnetwork)
library(igraph)
library(leaflet)
library(igraph)
library(ggrepel)
library(GGally)
library(visNetwork)

knitr::opts_chunk$set(echo = TRUE, 
                      fig.align="center", 
                      message = FALSE, 
                      warning = FALSE, 
                      comment = NA, 
                      echo = FALSE)
```



```{r, eval = F}
# TRADE DATA SET UP ----------------------------------------------------------------------
# Run once the first time you open it, and never again unless you delete the files

# trade flow data url
URL <- "http://www.cepii.fr/DATA_DOWNLOAD/baci/trade_flows/BACI_HS17_V202001.zip"

# create a file on the user's desktop 
download.file(url = URL, destfile = "~/Desktop/trade_flows.zip")
```

```{r}
# DATA READ IN ---------------------------------------------------------------------------

# unzip the file and save the .csv to the user's desktop
tradeflows <- unzip("~/Desktop/trade_flows.zip", exdir = "~/Desktop")

# read in trade flow data 
trade_flow <- read_csv(tradeflows)

# read in country code data 
country_codes <- read.csv("data sets/country_codes.csv")

# read in product code data 
product_codes <- read.csv("data sets/product_codes.csv")
```


```{r}
# DATA WRANGLING -------------------------------------------------------------------------

# remove extraneous variables 
countries <- country_codes %>%
  select(country_code, country_name_full) 

# recode levels to match with world map later (not entirely complete, add more if noticed)
countries$country_name_full <- recode(factor(countries$country_name_full), 
                                      "USA, Puerto Rico and US Virgin Islands" = "USA", 
                                      "Plurinational State of Bolivia" = "Bolivia", 
                                      "Russian Federation" = "Russia", 
                                      "France, Monaco" = "France",
                                      "Southern African Customs Union" = "South Africa", 
                                      "Viet Nam" = "Vietnam", 
                                      "United Republic of Tanzania" = "Tanzania", 
                                      "United Kingdom" = "UK", 
                                      "Norway, Svalbard and Jan Mayen" = "Norway")


# master data set with exports and imports (might be useful for networks)
trade_2018 <- trade_flow %>%
         # make variable names descriptive
  rename(year = t, product = k, exporter_code = i, importer_code = j, value = v, 
         quantity = q) %>%
  # year is always 2018 - unnecessary 
  select(-year) %>%
  # add exporter country names 
  left_join(countries, by = c("exporter_code" = "country_code")) %>%
  rename(exporter_name = country_name_full) %>%
  # add importer country names 
  left_join(countries, by = c("importer_code" = "country_code")) %>%
  rename(importer_name = country_name_full)

# separate data set for exports 
trade_exports <- trade_2018 %>%
  select(c(product, value, quantity, exporter_code, exporter_name))

# separate data set for imports 
trade_imports <- trade_2018 %>%
  select(c(product, value, quantity, importer_code, importer_name))

# proportion data sets 
whole_value <- sum(trade_2018$value)

export_prop <- trade_exports %>%
  group_by(exporter_name) %>%
  summarize(export_pct = 100*(sum(value)/whole_value))

import_prop <- trade_imports %>%
  group_by(importer_name) %>%
  summarize(import_pct = 100*(sum(value)/whole_value))
```

```{r}
# MAP SETUP ------------------------------------------------------------------------------

world <- map("world", fill = TRUE, plot = FALSE)

world$names <- str_replace(world$names, pattern = ":.*$", replacement = "")
```




# Interactive Graphs {.tabset .tabset-fade .tabset-pills}

## Infortmation


## Interactive Export Spatial Data

```{r exports}
# EXPORT MAP -----------------------------------------------------------------------------

export_pct_named <- export_prop$export_pct
names(export_pct_named) <- export_prop$exporter_name

world$export_pct <- export_pct_named[world$names]

mypalette <- colorNumeric(palette = "viridis", domain = world$export_pct, 
                           na.color = "transparent")

leaflet(world) %>%
  addTiles() %>%
  setView(lat=10, lng=0 , zoom=2) %>%
  addPolygons(color = "white", fillColor = ~mypalette(export_pct), weight = 1) %>%
  addLegend(pal = mypalette, values = ~export_pct, 
            title = "Export Percent", position = "bottomleft")
```

## Interactive Import Spatial Data

```{r imports}
# IMPORT MAP -----------------------------------------------------------------------------

import_pct_named <- import_prop$import_pct
names(import_pct_named) <- import_prop$importer_name

world$import_pct <- import_pct_named[world$names]

mypalette <- colorNumeric(palette = "viridis", domain = world$import_pct, 
                           na.color = "transparent")

leaflet(world) %>%
  addTiles() %>%
  setView(lat=10, lng=0 , zoom=2) %>%
  addPolygons(color = "white", fillColor = ~mypalette(import_pct), weight = 1) %>%
  addLegend(pal = mypalette, values = ~import_pct, 
            title = "Import Percent", position = "bottomleft")
```




You can make a bulleted list like this:

- item 1
- item 2
- item 3

###try this


## Numbered list

You can make a numbered list like this

1. First thing I want to say
2. Second thing I want to say
3. Third thing I want to say

