---
title: "data_wrangling"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(janitor)
library(lubridate)
library(maps)
library(datasets)
library(gapminder)
library(viridis)
```

## Load In Data


```{r}
#replace with your location of file
#t=Year, k=Product category (HS 6-digit code), i=Exporter (ISO 3-digit country code)
#j=Importer (ISO 3-digit country code), v=Value of the trade flow (in thousands current USD)
#q=Quantity (in metric tons)
tradedata2018 <- read.csv("/Users/samassaf1/Desktop/Data Science/sam's 231 git/Blog-Not-Stonks/Data/trade_2018_hs17.csv")

#replace with your location of file
#3-digit country code
countrycodes <- read.csv("/Users/samassaf1/Desktop/Data Science/sam's 231 git/Blog-Not-Stonks/Data/country_codes.csv")

#replace with your location of file
#6-digit code
productcodes <- read.csv("/Users/samassaf1/Desktop/Data Science/sam's 231 git/Blog-Not-Stonks/Data/product_codes_hs17.csv")

```

##Mutating Data
```{r}
#change variable names
tradedata2018_v1 <- tradedata2018 %>%
  select(c(year=t, product=k, Exporter=i, Importer=j, Value=v, Quantity=q)) %>%
  case_when(USA, Puerto Rico and US Virgin Islands)
#export
countrycodes_v1_export <- countrycodes %>%
  select(Exporter = country_code, Exporter_Name = country_name_full)
tradedata2018_export <- inner_join(tradedata2018_v1, countrycodes_v1_export, by = "Exporter")

#import
countrycodes_v1_import <- countrycodes %>%
  select(Importer = country_code, Importer_Name = country_name_full)
tradedata2018_import <- inner_join(tradedata2018_v1, countrycodes_v1_import, by = "Importer")

#combine the code so countries by name
tradedata2018_both <- left_join(tradedata2018_export, tradedata2018_import, by = c("year", "product", "Exporter", "Importer", "Value", "Quantity")) %>%
  select(year, product, Exporter_Name, Importer_Name, Value, Quantity) %>%
  mutate(Exporter_Name = as.character(Exporter_Name), Importer_Name = as.character(Importer_Name))

#try to only keep bigger countries becuase keep getting vector overload
wholevalue <- sum(tradedata2018_both$Value)


#proportion of total value country export
exportprop <- tradedata2018_both %>%
  select(year, region = Exporter_Name, Value) %>%
  group_by(year, region) %>%
  summarize(Value = sum(Value)) %>%
  mutate(prop = 100*(Value/wholevalue))

#proportion of total value country import
importprop <- tradedata2018_both %>%
  select(year, region = Importer_Name, Value) %>%
  group_by(year, region) %>%
  summarize(Value = sum(Value)) %>%
  mutate(prop = 100*(Value/wholevalue))


```

##Rough Graphs
```{r}

world_map <- map_data(map = "world"
                      , region = ".")
world_map <- world_map %>%
  select(c())
#inner joing world map by exported countries
exportgraphdata <- inner_join(world_map, exportprop, by = "region")

#graph for exported percentages
ggplot(exportgraphdata, aes(x = long, y = lat, group = group, fill = prop)) +
  geom_polygon(color = "grey") +
  theme_void() +
  coord_fixed(ratio = 1.3) +
  labs(title = "Proportion of Total Amount of Money (in $1000's of US $) a Country Exported", fill = "Percentage of Export", caption = "*Countries in white have no data*") +
  theme(legend.position="bottom") + 
  scale_fill_viridis(option = "viridis", direction = -1) 

#inner joing world map by imported countries
importgraphdata <- inner_join(world_map, importprop, by = "region")

#graph for exported percentages
ggplot(importgraphdata, aes(x = long, y = lat, group = group, fill = prop)) +
  geom_polygon(color = "grey") +
  theme_void() +
  coord_fixed(ratio = 1.3) +
  labs(title = "Proportion of Total Amount of Money (in $1000's of US $) a Country Imported", fill = "Percentage of Export", caption = "*Countries in white have no data*") +
  theme(legend.position="bottom") + 
  scale_fill_viridis(option = "plasma", direction = -1) 



```

